### ISSUE TITLE
SVG-billeder vises ikke i README

### ISSUE THREAD

**Issue by andreaskring** [magenta-aps/mora#17]
Der er sket et eller andet, efter vi er skiftet til SVG. På GitHub-forsiden vises SVG-billederne ikke.

**Comment by danchr** [comment]
Gah, det er en fejl i GitHub — og den er endda allerede rapporteret som github/markup#556 😞

**Comment by andreaskring** [comment]
Ok - skal vi så ikke lægge PNG'erne på igen, indtil de får fikset fejlen? Ellers er dokumentationen ikke så læsbar - vi kan evt. også flytte det til readthedocs, som du snakkede om.

**Comment by kivikakk** [comment]
We're working on a fix for this now; right now one of your SVGs doesn't render right because we're not handling the DOCTYPE correctly; see <https://raw.githubusercontent.com/magenta-aps/mora/master/docs/graphics/MORaModuler3.svg?sanitize=true>.

**Comment by kivikakk** [comment]
This is now fixed. (You may need to clear your cache.)

**Comment by andreaskring** [comment]
@kivikakk It is still not working correctly - if you take a look at the second image on the front page of the project, it can be seen that the image still looks strange.

**Comment by kivikakk** [comment]
It looks like this SVG makes extensive use of `<foreignObject>`, which our sanitizer doesn't support (because the content could be literally anything).

**Comment by andreaskring** [comment]
@kivikakk Ok - thanks for your fast response

**Comment by danchr** [comment]
@kivikakk Thank you for fixing it — and pointing out the error!

Might I suggest that you look into providing a more helpful error? For example, you could either respond with a dummy SVG saying something like “image rejected for security reasons” or perhaps simply drop the offending elements and insert comments in the SVG describing the reason. The latter offers slightly a more graceful failure at the cost of the *cause* of the error being more obscure — particularly to people who know little or nothing about images and SVG.

Again, thanks!

**Comment by kivikakk** [comment]
@danchr No problems!

Actually, we are just dropping the offending elements; inserting comments isn't a bad idea too, though! I'll have to see what I can do.

The text "[Not supported by viewer]" was from the SVG itself, in the `<switch>` element if `<foreignObject>` wasn't supported:

``` svg
<switch>
[…]
<text x="279" y="121" fill="#000000" text-anchor="middle" font-size="16px" font-family="Helvetica">[Not supported by viewer]</text>
</switch>
```

**Comment by danchr** [comment]
Ah, yes, I [see](https://github.com/magenta-aps/mora/tree/12cd4763a9f4f09a2d88b7b2c0a3a8ae7b175083) it now — I remember getting an error, but that might be before your fix. Thanks again!

Interestingly, you don't seem to sanitise the [actual SVG itself](https://github.com/magenta-aps/mora/blob/12cd4763a9f4f09a2d88b7b2c0a3a8ae7b175083/docs/graphics/MORaModuler3.svg) itself — it's loaded using a data URI. Assuming the original reason for sanitising the SVG was a security vulnerability, wouldn't that be insecure as well? Otherwise, the same data URI trick should work for markup.

**Comment by kivikakk** [comment]
The blob view uses a different system for rendering all kinds of data; it has a fairly complex architecture which involves a bunch of async stuff and `<iframe>` for sandboxing, which we couldn't reuse in markup (because it'd look terrible while loading and resizing the iframe dynamically after load).

**Comment by danchr** [comment]
Ah, I see, thanks!
